"""Report generator — CSV and PDF for Matching, Hiring Score, and Skill Gap reports."""

import csv
import io
from datetime import datetime

from fpdf import FPDF


# ── Shared helpers ─────────────────────────────────────────────────────────

def _now() -> str:
    return datetime.now().strftime("%Y-%m-%d %H:%M")


def _safe(value) -> str:
    """Convert any value to a clean ASCII string safe for PDF/CSV."""
    text = str(value or "-").replace("\n", " ").strip()
    # Strip non-latin-1 characters so fpdf2 core fonts don't crash
    return text.encode("latin-1", errors="replace").decode("latin-1")


# ══════════════════════════════════════════════════════════════════════════
#  BASE PDF
# ══════════════════════════════════════════════════════════════════════════

class _BasePDF(FPDF):
    BRAND   = "TalentAI · Recruitment Copilot"
    PRIMARY = (124, 58, 237)   # purple
    DARK    = (30,  27,  75)   # dark indigo
    LIGHT   = (241, 245, 249)  # slate-100
    MUTED   = (100, 116, 139)  # slate-500
    GREEN   = (16,  185, 129)
    RED     = (239,  68,  68)
    AMBER   = (245, 158,  11)
    BLUE    = (59,  130, 246)

    def header(self):
        self.set_fill_color(*self.DARK)
        self.rect(0, 0, 210, 22, "F")
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(*self.PRIMARY)
        self.set_xy(10, 6)
        self.cell(0, 10, self.BRAND, ln=False)
        self.set_font("Helvetica", "", 8)
        self.set_text_color(*self.MUTED)
        self.set_xy(0, 6)
        self.cell(200, 10, _now(), align="R")
        self.ln(18)

    def footer(self):
        self.set_y(-14)
        self.set_font("Helvetica", "", 8)
        self.set_text_color(*self.MUTED)
        self.cell(0, 10, f"Page {self.page_no()} - Generated by TalentAI", align="C")

    def section_title(self, text: str) -> None:
        self.set_font("Helvetica", "B", 10)
        self.set_text_color(*self.PRIMARY)
        self.set_fill_color(245, 243, 255)
        self.cell(0, 8, f"  {text}", ln=True, fill=True)
        self.ln(2)

    def kv_row(self, key: str, value: str, color=None) -> None:
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*self.MUTED)
        self.cell(55, 7, key + ":", ln=False)
        self.set_font("Helvetica", "", 9)
        self.set_text_color(*(color or self.DARK))
        # Use remaining page width so text never overflows
        self.multi_cell(self.epw - 55, 7, _safe(value))

    def score_bar(self, label: str, score: float, color: tuple) -> None:
        """Render a labeled progress bar."""
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*self.MUTED)
        self.cell(55, 6, label + ":", ln=False)
        # bar background
        x, y = self.get_x(), self.get_y()
        bar_w = 100
        self.set_fill_color(226, 232, 240)
        self.rect(x, y + 1, bar_w, 4, "F")
        # bar fill
        fill_w = round(bar_w * score / 100)
        self.set_fill_color(*color)
        self.rect(x, y + 1, fill_w, 4, "F")
        # score text
        self.set_xy(x + bar_w + 3, y)
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*color)
        self.cell(20, 6, f"{score}%", ln=True)

    def pill_row(self, label: str, skills: list[str], color: tuple) -> None:
        """Render a label + comma-separated skill list."""
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*self.MUTED)
        self.cell(55, 6, label + ":", ln=False)
        self.set_font("Helvetica", "", 9)
        self.set_text_color(*color)
        text = ", ".join(skills) if skills else "None"
        # epw = effective page width; subtract label column so content fits
        self.multi_cell(self.epw - 55, 6, text)

    def big_score(self, score: float, grade: str, verdict: str, color: tuple) -> None:
        self.set_font("Helvetica", "B", 32)
        self.set_text_color(*color)
        self.cell(0, 18, f"{score}%  {grade}", ln=True, align="C")
        self.set_font("Helvetica", "", 11)
        self.set_text_color(*self.MUTED)
        self.cell(0, 8, verdict, ln=True, align="C")
        self.ln(4)


def _grade_info(score: float) -> tuple[str, str, tuple]:
    if score >= 85: return "A+", "Excellent",  (16,  185, 129)
    if score >= 70: return "A",  "Strong",      (52,  211, 153)
    if score >= 55: return "B",  "Good",        (245, 158,  11)
    if score >= 40: return "C",  "Average",     (251, 146,  60)
    return              "D",  "Weak",        (239,  68,  68)


# ══════════════════════════════════════════════════════════════════════════
#  1. CANDIDATE MATCHING REPORT
# ══════════════════════════════════════════════════════════════════════════

def matching_csv(result: dict) -> bytes:
    """Return CSV bytes for a matching result dict."""
    buf = io.StringIO()
    w   = csv.writer(buf)

    cand   = result["candidate"]
    job    = result["job"]
    skills = result["skills"]
    exp    = result["experience"]
    edu    = result["education"]
    certs  = result["certs"]

    w.writerow(["Candidate Matching Report", _now()])
    w.writerow([])
    w.writerow(["CANDIDATE"])
    w.writerow(["Name",  _safe(cand.get("name"))])
    w.writerow(["Email", _safe(cand.get("email"))])
    w.writerow([])
    w.writerow(["JOB"])
    w.writerow(["Title",      _safe(job.get("job_title"))])
    w.writerow(["Department", _safe(job.get("department"))])
    w.writerow(["Location",   _safe(job.get("location"))])
    w.writerow([])
    w.writerow(["SKILL ANALYSIS"])
    w.writerow(["Match Score",       f"{skills['score']}%"])
    w.writerow(["Matched Skills",    ", ".join(skills["matched"])])
    w.writerow(["Missing Skills",    ", ".join(skills["missing"])])
    w.writerow(["Additional Skills", ", ".join(skills["additional"])])
    w.writerow([])
    w.writerow(["EXPERIENCE"])
    w.writerow(["JD Requires",     exp["jd_level"]])
    w.writerow(["Candidate Level", exp["candidate_level"]])
    w.writerow(["Status",          exp["status"]])
    w.writerow([])
    w.writerow(["EDUCATION"])
    w.writerow(["JD Requires",  edu["jd_requires"]])
    w.writerow(["Candidate Has", edu["candidate_has"]])
    w.writerow(["Status",        edu["status"]])
    w.writerow([])
    w.writerow(["CERTIFICATIONS"])
    if "jd_requires" in certs:
        w.writerow(["JD Requires",  certs["jd_requires"]])
        w.writerow(["Candidate Has", certs["candidate_has"]])
    w.writerow(["Status", certs["status"]])

    return buf.getvalue().encode()


def matching_pdf(result: dict) -> bytes:
    cand   = result["candidate"]
    job    = result["job"]
    skills = result["skills"]
    exp    = result["experience"]
    edu    = result["education"]
    certs  = result["certs"]

    score  = skills["score"]
    grade, verdict, clr = _grade_info(score)

    pdf = _BasePDF()
    pdf.add_page()

    # ── Title ──
    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(*pdf.DARK)
    pdf.cell(0, 10, "Candidate Matching Report", ln=True, align="C")
    pdf.ln(2)

    # ── Big score ──
    pdf.big_score(score, grade, verdict, clr)

    # ── Candidate + Job ──
    pdf.section_title("Candidate")
    pdf.kv_row("Name",  cand.get("name"))
    pdf.kv_row("Email", cand.get("email"))
    pdf.ln(3)

    pdf.section_title("Job Description")
    pdf.kv_row("Title",      job.get("job_title"))
    pdf.kv_row("Department", job.get("department"))
    pdf.kv_row("Location",   job.get("location"))
    pdf.ln(3)

    # ── Skill analysis ──
    pdf.section_title("Skill Analysis")
    pdf.score_bar("Match Score", score, clr)
    pdf.ln(2)
    pdf.pill_row("Matched Skills",    skills["matched"],    pdf.GREEN)
    pdf.pill_row("Missing Skills",    skills["missing"],    pdf.RED)
    pdf.pill_row("Additional Skills", skills["additional"], pdf.BLUE)
    pdf.ln(3)

    # ── Experience ──
    pdf.section_title("Experience")
    pdf.kv_row("JD Requires",     exp["jd_level"])
    pdf.kv_row("Candidate Level", exp["candidate_level"])
    pdf.kv_row("Status",          exp["status"])
    pdf.ln(3)

    # ── Education ──
    pdf.section_title("Education")
    pdf.kv_row("JD Requires",  edu["jd_requires"])
    pdf.kv_row("Candidate Has", edu["candidate_has"])
    pdf.kv_row("Status",        edu["status"])
    pdf.ln(3)

    # ── Certifications ──
    pdf.section_title("Certifications")
    if "jd_requires" in certs:
        pdf.kv_row("JD Requires",  certs["jd_requires"])
        pdf.kv_row("Candidate Has", certs["candidate_has"])
    pdf.kv_row("Status", certs["status"])

    return bytes(pdf.output())


# ══════════════════════════════════════════════════════════════════════════
#  2. HIRING SCORE REPORT
# ══════════════════════════════════════════════════════════════════════════

def hiring_score_csv(result: dict) -> bytes:
    buf = io.StringIO()
    w   = csv.writer(buf)

    cand  = result["candidate"]
    job   = result["job"]
    grade, verdict, _ = _grade_info(result["overall"])

    w.writerow(["Hiring Score Report", _now()])
    w.writerow([])
    w.writerow(["CANDIDATE"])
    w.writerow(["Name",  _safe(cand.get("name"))])
    w.writerow(["Email", _safe(cand.get("email"))])
    w.writerow([])
    w.writerow(["JOB"])
    w.writerow(["Title",      _safe(job.get("job_title"))])
    w.writerow(["Department", _safe(job.get("department"))])
    w.writerow([])
    w.writerow(["SCORES"])
    w.writerow(["Overall Score",       f"{result['overall']}%"])
    w.writerow(["Grade",               grade])
    w.writerow(["Verdict",             verdict])
    w.writerow(["Skill Score (70%)",   f"{result['skill']}%"])
    w.writerow(["Experience Score (20%)", f"{result['experience']}%"])
    w.writerow(["Certification Score (10%)", f"{result['cert']}%"])
    w.writerow([])
    w.writerow(["FORMULA"])
    w.writerow([f"({result['skill']}% × 0.70) + ({result['experience']}% × 0.20) + ({result['cert']}% × 0.10) = {result['overall']}%"])
    w.writerow([])
    w.writerow(["Skills Matched", f"{result['matched']} of {result['total_jd']} required"])

    return buf.getvalue().encode()


def hiring_score_pdf(result: dict) -> bytes:
    cand  = result["candidate"]
    job   = result["job"]
    grade, verdict, clr = _grade_info(result["overall"])

    pdf = _BasePDF()
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(*pdf.DARK)
    pdf.cell(0, 10, "Hiring Score Report", ln=True, align="C")
    pdf.ln(2)

    pdf.big_score(result["overall"], grade, verdict, clr)

    pdf.section_title("Candidate")
    pdf.kv_row("Name",  cand.get("name"))
    pdf.kv_row("Email", cand.get("email"))
    pdf.ln(3)

    pdf.section_title("Job Description")
    pdf.kv_row("Title",      job.get("job_title"))
    pdf.kv_row("Department", job.get("department"))
    pdf.ln(3)

    pdf.section_title("Score Breakdown")
    pdf.score_bar("Overall Score",        result["overall"],    clr)
    pdf.score_bar("Skill Score (70%)",    result["skill"],      pdf.PRIMARY)
    pdf.score_bar("Experience Score (20%)", result["experience"], pdf.BLUE)
    pdf.score_bar("Cert Score (10%)",     result["cert"],       pdf.GREEN)
    pdf.ln(3)

    pdf.section_title("Formula")
    pdf.set_font("Helvetica", "", 9)
    pdf.set_text_color(*pdf.MUTED)
    formula = (
        f"Overall = (Skill x 70%) + (Experience x 20%) + (Cert x 10%)\n"
        f"       = ({result['skill']}% x 0.70) + ({result['experience']}% x 0.20) + ({result['cert']}% x 0.10)\n"
        f"       = {round(result['skill']*0.70,1)} + {round(result['experience']*0.20,1)} + {round(result['cert']*0.10,1)}\n"
        f"       = {result['overall']}%"
    )
    pdf.multi_cell(0, 6, formula)
    pdf.ln(3)

    pdf.section_title("Recommendation")
    recs = {
        "A+": "Strongly Recommend Hiring - Top candidate, schedule interview immediately.",
        "A":  "Recommend Hiring - Strong candidate, proceed to next round.",
        "B":  "Consider with Conditions - Good candidate, may need minor upskilling.",
        "C":  "Borderline - Average fit, consider only if no better options.",
        "D":  "Not Recommended - Significant gaps, does not meet requirements.",
    }
    pdf.set_font("Helvetica", "B", 10)
    pdf.set_text_color(*clr)
    pdf.multi_cell(0, 7, recs.get(grade, "-"))

    return bytes(pdf.output())


# ══════════════════════════════════════════════════════════════════════════
#  3. SKILL GAP REPORT
# ══════════════════════════════════════════════════════════════════════════

_RECOMMENDATIONS: dict[str, dict] = {
    "aws": {"course": "AWS Cloud Practitioner", "platform": "AWS Training", "level": "Beginner"},
    "azure": {"course": "Azure Fundamentals AZ-900", "platform": "Microsoft Learn", "level": "Beginner"},
    "gcp": {"course": "Google Cloud Fundamentals", "platform": "Google Cloud", "level": "Beginner"},
    "docker": {"course": "Docker Fundamentals", "platform": "Docker Docs", "level": "Beginner"},
    "kubernetes": {"course": "Kubernetes Basics", "platform": "Kubernetes.io", "level": "Intermediate"},
    "terraform": {"course": "Terraform Getting Started", "platform": "HashiCorp", "level": "Intermediate"},
    "ansible": {"course": "Ansible for Beginners", "platform": "Red Hat", "level": "Beginner"},
    "jenkins": {"course": "Jenkins CI/CD Pipeline", "platform": "Jenkins Docs", "level": "Intermediate"},
    "ci/cd": {"course": "CI/CD Pipeline Fundamentals", "platform": "GitLab Learn", "level": "Intermediate"},
    "python": {"course": "Python for Everybody", "platform": "Coursera", "level": "Beginner"},
    "java": {"course": "Java Programming Masterclass", "platform": "Udemy", "level": "Beginner"},
    "javascript": {"course": "JavaScript: The Complete Guide", "platform": "Udemy", "level": "Beginner"},
    "typescript": {"course": "TypeScript Fundamentals", "platform": "Pluralsight", "level": "Intermediate"},
    "go": {"course": "Go Programming Language", "platform": "Tour of Go", "level": "Intermediate"},
    "rust": {"course": "The Rust Programming Language", "platform": "Rust Book", "level": "Advanced"},
    "react": {"course": "React - The Complete Guide", "platform": "Udemy", "level": "Intermediate"},
    "angular": {"course": "Angular - The Complete Guide", "platform": "Udemy", "level": "Intermediate"},
    "vue": {"course": "Vue.js Essentials", "platform": "Vue Mastery", "level": "Beginner"},
    "node.js": {"course": "Node.js Complete Course", "platform": "Udemy", "level": "Intermediate"},
    "django": {"course": "Django for Beginners", "platform": "Django Docs", "level": "Intermediate"},
    "flask": {"course": "Flask Web Development", "platform": "Flask Docs", "level": "Beginner"},
    "fastapi": {"course": "FastAPI Tutorial", "platform": "FastAPI Docs", "level": "Intermediate"},
    "sql": {"course": "SQL for Data Analysis", "platform": "Mode Analytics", "level": "Beginner"},
    "postgresql": {"course": "PostgreSQL Tutorial", "platform": "PostgreSQL.org", "level": "Beginner"},
    "mongodb": {"course": "MongoDB Basics", "platform": "MongoDB Univ.", "level": "Beginner"},
    "pandas": {"course": "Pandas for Data Analysis", "platform": "Kaggle", "level": "Beginner"},
    "tensorflow": {"course": "TensorFlow Developer Certificate", "platform": "Google", "level": "Advanced"},
    "pytorch": {"course": "PyTorch Deep Learning", "platform": "fast.ai", "level": "Advanced"},
    "scikit-learn": {"course": "Scikit-learn ML Course", "platform": "Kaggle", "level": "Intermediate"},
    "spark": {"course": "Apache Spark Fundamentals", "platform": "Databricks", "level": "Advanced"},
    "git": {"course": "Git & GitHub Crash Course", "platform": "freeCodeCamp", "level": "Beginner"},
    "linux": {"course": "Linux Command Line Basics", "platform": "edX", "level": "Beginner"},
    "tableau": {"course": "Tableau Desktop Specialist", "platform": "Tableau", "level": "Intermediate"},
    "power bi": {"course": "Power BI Data Analyst", "platform": "Microsoft Learn", "level": "Intermediate"},
    "kafka": {"course": "Apache Kafka Fundamentals", "platform": "Confluent", "level": "Advanced"},
    "agile": {"course": "Agile Fundamentals", "platform": "Scrum.org", "level": "Beginner"},
    "scrum": {"course": "Professional Scrum Master", "platform": "Scrum.org", "level": "Beginner"},
}
_DEFAULT_REC = {"course": "Search on Udemy / Coursera", "platform": "Online Learning", "level": "Beginner"}


def skill_gap_csv(result: dict) -> bytes:
    buf = io.StringIO()
    w   = csv.writer(buf)

    cand = result["candidate"]
    job  = result["job"]
    a    = result["analysis"]

    w.writerow(["Skill Gap Report", _now()])
    w.writerow([])
    w.writerow(["CANDIDATE"])
    w.writerow(["Name",  _safe(cand.get("name"))])
    w.writerow(["Email", _safe(cand.get("email"))])
    w.writerow([])
    w.writerow(["JOB"])
    w.writerow(["Title",      _safe(job.get("job_title"))])
    w.writerow(["Department", _safe(job.get("department"))])
    w.writerow([])
    w.writerow(["SUMMARY"])
    w.writerow(["Total JD Skills",    a["total_jd"]])
    w.writerow(["Matched Skills",     len(a["matched"])])
    w.writerow(["Missing Skills",     len(a["missing"])])
    w.writerow(["Additional Skills",  len(a["extra"])])
    w.writerow(["Match %",            f"{a['match_pct']}%"])
    w.writerow(["Skill Gap %",        f"{a['gap_pct']}%"])
    w.writerow([])
    w.writerow(["MATCHED SKILLS"])
    w.writerow([", ".join(a["matched"]) or "None"])
    w.writerow([])
    w.writerow(["MISSING SKILLS"])
    w.writerow([", ".join(a["missing"]) or "None"])
    w.writerow([])
    w.writerow(["LEARNING RECOMMENDATIONS"])
    w.writerow(["Skill", "Course", "Platform", "Level"])
    for skill in a["missing"]:
        rec = _RECOMMENDATIONS.get(skill.lower(), _DEFAULT_REC)
        w.writerow([skill.title(), rec["course"], rec["platform"], rec["level"]])

    return buf.getvalue().encode()


def skill_gap_pdf(result: dict) -> bytes:
    cand = result["candidate"]
    job  = result["job"]
    a    = result["analysis"]

    gap  = a["gap_pct"]
    if gap == 0:
        gap_clr = (16, 185, 129)
    elif gap <= 30:
        gap_clr = (245, 158, 11)
    elif gap <= 60:
        gap_clr = (251, 146, 60)
    else:
        gap_clr = (239, 68, 68)

    pdf = _BasePDF()
    pdf.add_page()

    pdf.set_font("Helvetica", "B", 16)
    pdf.set_text_color(*pdf.DARK)
    pdf.cell(0, 10, "Skill Gap Analysis Report", ln=True, align="C")
    pdf.ln(2)

    # ── Gap score ──
    pdf.set_font("Helvetica", "B", 28)
    pdf.set_text_color(*gap_clr)
    pdf.cell(0, 14, f"Skill Gap: {gap}%  |  Match: {a['match_pct']}%", ln=True, align="C")
    pdf.ln(4)

    pdf.section_title("Candidate")
    pdf.kv_row("Name",  cand.get("name"))
    pdf.kv_row("Email", cand.get("email"))
    pdf.ln(3)

    pdf.section_title("Job Description")
    pdf.kv_row("Title",      job.get("job_title"))
    pdf.kv_row("Department", job.get("department"))
    pdf.ln(3)

    pdf.section_title("Summary")
    pdf.score_bar("Match %",    a["match_pct"], pdf.GREEN)
    pdf.score_bar("Skill Gap %", a["gap_pct"],  gap_clr)
    pdf.ln(2)
    pdf.kv_row("Total JD Skills",   str(a["total_jd"]))
    pdf.kv_row("Matched Skills",    str(len(a["matched"])))
    pdf.kv_row("Missing Skills",    str(len(a["missing"])))
    pdf.kv_row("Additional Skills", str(len(a["extra"])))
    pdf.ln(3)

    pdf.section_title("Matched Skills")
    pdf.pill_row("Skills", a["matched"], pdf.GREEN)
    pdf.ln(3)

    pdf.section_title("Missing Skills")
    pdf.pill_row("Skills", a["missing"], pdf.RED)
    pdf.ln(3)

    # ── Learning recommendations table ──
    if a["missing"]:
        pdf.section_title("Learning Recommendations")
        # Table header
        pdf.set_fill_color(*pdf.DARK)
        pdf.set_text_color(255, 255, 255)
        pdf.set_font("Helvetica", "B", 8)
        pdf.cell(35, 7, "Skill",    border=0, fill=True)
        pdf.cell(75, 7, "Course",   border=0, fill=True)
        pdf.cell(45, 7, "Platform", border=0, fill=True)
        pdf.cell(0,  7, "Level",    border=0, fill=True, ln=True)

        level_colors = {
            "Beginner":     (16,  185, 129),
            "Intermediate": (245, 158,  11),
            "Advanced":     (239,  68,  68),
        }
        for i, skill in enumerate(a["missing"]):
            rec = _RECOMMENDATIONS.get(skill.lower(), _DEFAULT_REC)
            fill = i % 2 == 0
            pdf.set_fill_color(248, 250, 252) if fill else pdf.set_fill_color(255, 255, 255)
            pdf.set_text_color(*pdf.DARK)
            pdf.set_font("Helvetica", "B", 8)
            pdf.cell(35, 6, skill.title(), border=0, fill=fill)
            pdf.set_font("Helvetica", "", 8)
            pdf.cell(75, 6, rec["course"][:40], border=0, fill=fill)
            pdf.cell(45, 6, rec["platform"],    border=0, fill=fill)
            lclr = level_colors.get(rec["level"], pdf.MUTED)
            pdf.set_text_color(*lclr)
            pdf.set_font("Helvetica", "B", 8)
            pdf.cell(0,  6, rec["level"], border=0, fill=fill, ln=True)

    return bytes(pdf.output())
